### ISSUE TITLE
It isn't working anymore

### ISSUE THREAD

**Issue by keexers** [SealedSaucer/Online-Forever#13]
Last 2 months, the online-forever worked like a charm. But after the recent discord update, It isn't working anymore. I don't know if it's the discord update or it's just my issue.

https://streamable.com/ulqvnb

**Comment by SealedSaucer** [comment]
Hey, it's the problem of your repl. Try cloning it again into a new repl.

**Comment by skyoutMP** [comment]
same issue

`python3 main.py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
 * Serving Flask app ''
 * Debug mode: off
    client.run(os.getenv("MY TOKEN HERE"))
  File "/home/runner/Onliner/venv/lib/python3.8/site-packages/discord/client.py", line 727, in run
    asyncio.run(runner())
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/Onliner/venv/lib/python3.8/site-packages/discord/client.py", line 724, in runner
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.18.0.22:8080
    await self.start(*args, **kwargs)
  File "/home/runner/Onliner/venv/lib/python3.8/site-packages/discord/client.py", line 697, in start
Press CTRL+C to quit
    await self.login(token)
  File "/home/runner/Onliner/venv/lib/python3.8/site-packages/discord/client.py", line 568, in login
    data = await state.http.static_login(token.strip())
AttributeError: 'NoneType' object has no attribute 'strip'
172.18.0.1 - - [02/Sep/2022 19:59:13] "GET / HTTP/1.1" 200 -
signal: terminated`

**Comment by SealedSaucer** [comment]
Stop putting your token inside the code. I have never said to add your token inside the code. The video clearly shows and explains you have to put your token inside Secrets. If you are not sure about the installation/setup process, check the video linked in the readme.
