### ISSUE TITLE
My account Token dont work

### ISSUE THREAD

**Issue by Herobr1ne** [SealedSaucer/Online-Forever#15]
Hey, have problems with my account token. Tryed with 2 different accounts but it always say "discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized"

`"C:\Users\Steven Arnold\PycharmProjects\SelfBot\venv\Scripts\python.exe" "C:/Users/Steven Arnold/PycharmProjects/SelfBot/main.py"
Traceback (most recent call last):
  File "C:\Users\Steven Arnold\PycharmProjects\SelfBot\venv\lib\site-packages\discord\http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Steven Arnold\PycharmProjects\SelfBot\venv\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Steven Arnold\PycharmProjects\SelfBot\main.py", line 30, in <module>
    client.run("Here is my Token!")
  File "C:\Users\Steven Arnold\PycharmProjects\SelfBot\venv\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\Steven Arnold\PycharmProjects\SelfBot\venv\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Steven Arnold\PycharmProjects\SelfBot\venv\lib\site-packages\discord\client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "C:\Users\Steven Arnold\PycharmProjects\SelfBot\venv\lib\site-packages\discord\client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Steven Arnold\PycharmProjects\SelfBot\venv\lib\site-packages\discord\http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000025B4127FC10>
Traceback (most recent call last):
  File "C:\Users\Steven Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Steven Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Steven Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Steven Arnold\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

Tokens look like this (I changed some Characters and letter for Security Reason xD):
1. "BfA4NTFyLPB0MTkxOTIyMTk8.GxmH9p.PmXFtwFWIlrGPnWhEZimxc24jpB"
2.  "mfa.Z7loRFVLgaXJ_rKvuidKp6oZu2i7FsBW5LAvhFOvPGpduSHwzn2YW32sgRBbKMqLH57_QrWOTFxAsPL1JKG"

**Comment by SealedSaucer** [comment]
The tokens are not valid. Please check your token before adding it into the code.
