### ISSUE TITLE
Local Installation doesnt work

### ISSUE THREAD

**Issue by riotxxyz** [SealedSaucer/Online-Forever#34]
keeps saying No module named linecache can be found

command prompt:

 onlineforever>pip install -r requirements.txt
 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\pip.exe\__main__.py", line 4, in <module>
  File "C:\Python311\Lib\site-packages\_distutils_hack\__init__.py", line 97, in find_spec
    return method()
           ^^^^^^^^
  File "C:\Python311\Lib\site-packages\_distutils_hack\__init__.py", line 145, in spec_for_pip
    if self.pip_imported_during_build():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\_distutils_hack\__init__.py", line 155, in pip_imported_during_build
    import traceback
  File "C:\Python311\Lib\traceback.py", line 5, in <module>
    import linecache
ModuleNotFoundError: No module named 'linecache'

**Comment by riotxxyz** [comment]
when i try to run the main file it says

onlineforever>python hello.py
Traceback (most recent call last):
  File "C:\Users\xxlou\Desktop\onlineforever\hello.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by SealedSaucer** [comment]
Message me on discord or telegram: [Click here](https://phantom.is-a.dev/verify).
